import React from 'react';
import AppSidebar from '../components/AppSidebar';
import AppHeader from '../components/AppHeader';

import { CContainer } from '@coreui/react';

function Layout({ children }: { children: React.ReactNode }) {
    return (
        <div className="d-flex">
            <title>관리자</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <AppSidebar />
            <CContainer
                className="d-flex flex-column min-vh-100 bg-light"
                fluid
            >
                <AppHeader />
                <div className="body flex-grow-1">{children}</div>
            </CContainer>
        </div>
    );
}

export default Layout;
