import React from 'react';

function Layout({ children }: { children: React.ReactNode }) {
    return (
        <>
            <title>관리자</title>
            <meta
                name="description"
                content="Generated by create next app"
            />
            <link rel="icon" href="/favicon.ico" />
            <div>{children}</div>
        </>
    );
}

export default Layout;
